### ISSUE TITLE
RuntimeError: size mismatch?

### ISSUE THREAD

**Issue by GarrickLin** [YuliangXiu/MobilePose-pytorch#2]
```
python training.py --model=resnet --gpu=0
GPU NUM: 1
Traceback (most recent call last):
  File "training.py", line 120, in <module>
    outputs = net(images)
  File "/home/lxy/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxy/workspace/python/MobilePose-pytorch/networks.py", line 47, in forward
    pose_out = self.resnet(x)
  File "/home/lxy/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxy/anaconda2/lib/python2.7/site-packages/torchvision/models/resnet.py", line 151, in forward
    x = self.fc(x)
  File "/home/lxy/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxy/anaconda2/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/lxy/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:247
```

**Comment by GarrickLin** [comment]
fix it using `inputsize = 224`
