### ISSUE TITLE
missing imgaug

### ISSUE THREAD

**Issue by tracyliang18** [YuliangXiu/MobilePose-pytorch#3]
Traceback (most recent call last):
  File "training.py", line 22, in <module>
    from dataloader import *
  File "/unsullied/sharefs/liangjiajun/workspace/research-2018/MobilePose-pytorch/dataloader.py", line 181, in <module>
    import imgaug as ia
ImportError: No module named 'imgaug'

**Comment by GarrickLin** [comment]
just `pip install imgaug`
