### ISSUE TITLE
No module named 'imgaug'

### ISSUE THREAD

**Issue by tlhcelik** [YuliangXiu/MobilePose-pytorch#43]
Hi,
when i try run run_webcam.py  module raise this exception. I install imgaug for this way:

`pip3 install imgaug`

```python
pip3 install imgaug
Defaulting to user installation because normal site-packages is not writeable
Collecting imgaug
  Using cached imgaug-0.4.0-py2.py3-none-any.whl (948 kB)
Requirement already satisfied: matplotlib in /home/mpg-agx/.local/lib/python3.6/site-packages (from imgaug) (3.2.1)
Requirement already satisfied: scikit-image>=0.14.2 in /home/mpg-agx/.local/lib/python3.6/site-packages (from imgaug) (0.16.2)
Requirement already satisfied: imageio in /home/mpg-agx/.local/lib/python3.6/site-packages (from imgaug) (2.8.0)
Requirement already satisfied: Pillow in /home/mpg-agx/.local/lib/python3.6/site-packages (from imgaug) (6.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from imgaug) (1.4.1)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.6/dist-packages (from imgaug) (1.18.2)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from imgaug) (1.14.0)
Collecting Shapely
  Using cached Shapely-1.7.0.tar.gz (349 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ima7o4jb/Shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ima7o4jb/Shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ima7o4jb/Shapely/pip-egg-info
         cwd: /tmp/pip-install-ima7o4jb/Shapely/
    Complete output (11 lines):
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ima7o4jb/Shapely/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-ima7o4jb/Shapely/shapely/_buildcfg.py", line 170, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "/tmp/pip-install-ima7o4jb/Shapely/shapely/_buildcfg.py", line 164, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by YuliangXiu** [comment]
please refer to this installation instruction 

https://imgaug.readthedocs.io/en/latest/source/installation.html
